### ISSUE TITLE
Checkpoint 1 ready for review

### ISSUE THREAD

**Issue by dmueller3** [dmueller3/FantasyFootballScheduler#1]
@pawaitemadisoncollege

My checkpoint 1 is ready for review. I struggled a bit with the project plan as I'm not sure on the scope of things before I begin working on them. I believe everything else should be in a good place!

**Comment by pawaitemadisoncollege** [comment]
Hi @dmueller3!

You are off to a great start, and I'm really looking forward to seeing the first parts of this built out! 

**Problem statement** 

Does an excellent job clearly explaining the problem and the solution. Very effective use of a persona for this! 

- [x] Would it be useful to link to the NFL fantasy football website at all, for those who aren't familiar with it?

**User stories w/ MVP stories identified** 

While the user stories are not written using typical user story syntax, "as a logged in user I want to.... so that .... ", I think your list does a good job identifying the functionality of the website, and MVP is clearly marked.

- [ ] In reviewing the MVP functionality and considering the requirements for class,  delete and update scenarios should be identified for the MVP. I see you have delete as non-mvp. Is it realistic to mark that MVP and add another story that would handle the edit/update scenario? Upon further review with the screens... maybe the New Schedule results screen handles the update since there is a region and save button? Not sure if that's a true update in the database crud sense... 

- [ ] Thinking about a web service or api that could be used in your project: there a number of possibilities - a quick search of rapidapi.com yields a number of apis to explore: https://rapidapi.com/search?term%3Dnfl%26sortBy%3DByRelevance. Scraping using a tool like jsoup is an option too (and possible team project idea!)

**Wireframes**. Good work on these! The wireframes clearly communicate what each page will do and seem to match up with the user stories above. Reviewing the hand-drawn style was a change! 

- [ ] Something to know is that we'll be using AWS cognito for sign up/sign in capability, so there are some screens that you may not have to worry about as they can be provided by Cognito itself.  We'll learn more about this in week 7.

**Project Plan** A good start!  I did not pick through the schedule with a fine-toothed comb, but it seems to be that user stories are all represented. The schedule will obviously flex and change, but I think this is a solid start. 

- [ ] It might be a good idea to regularly review and revise the plan  - I'd say weekly.
- [ ] You may want to bump the login pages portion from week 4 to week 7 when we cover cognito. 

**Reflection/Time log** Keep up the good work with this. 

- [ ] Document all time spent in class, not just time on your indie project. This helps us both evaluate what might need more or less time!


**********
**Status: met**
